<div align="center">
  <h1> 30 D칤as de JavaScript: Manejo de Errores</h1>
  <a class="header-badge" target="_blank" href="https://www.linkedin.com/in/asabeneh/">
  <img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social">
  </a>
  <a class="header-badge" target="_blank" href="https://twitter.com/Asabeneh">
  <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/asabeneh?style=social">
  </a>

<sub>Autor:
<a href="https://www.linkedin.com/in/asabeneh/" target="_blank">Asabeneh Yetayeh</a><br>
<small> Enero, 2020</small>
</sub>

</div>

[<< D칤a 13](../dia_13_Metodos_del_Objeto_Console/dia_13_metodos_del_objeto_console.md) | [D칤a 15>>](..)

![Thirty Days Of JavaScript](../images/banners/day_1_14.png)

- [D칤a 14](#d칤a-14)
  - [Manejo de Errores](#manejo-de-errores)
    - [Tipo de Error](#tipo-de-error)
  - [Ejercicios](#ejercicios)
    - [Ejercicios:Nivel 1](#ejerciciosnivel-1)
    - [Ejercicios: Nivel 2](#ejerciciosnivel-2)
    - [Ejercicios:Nivel 3](#ejerciciosnivel-3)

# D칤a 14

## Manejo de Errores

JavaScript es un lenguaje de tipado libre. Algunas veces obtendr치 un error en tiempo de ejecuci칩n cuando intente acceder a una variable no definida o llamar a una funci칩n no definida, etc.

JavaScript, al igual que python o Java, proporciona un mecanismo de gesti칩n de errores para capturar los errores en tiempo de ejecuci칩n mediante el bloque try-catch-finally.

```js
try {
  // c칩digo que puede arrojar un error
} catch (err) {
  // c칩digo a ejecutar si se produce un error
} finally {
  // c칩digo que se ejecutar치 independientemente de que se produzca un error o no
}
```

**try**: envuelve el c칩digo sospechoso que puede arrojar un error en un bloque try. La sentencia try nos permite definir un bloque de c칩digo para que se compruebe si hay errores mientras se ejecuta.

**catch**: escribe c칩digo para hacer algo en el bloque catch cuando se produce un error. El bloque catch puede tener par치metros que le dar치n informaci칩n sobre el error. El bloque Catch se utiliza para registrar un error o mostrar mensajes espec칤ficos al usuario.

**finally**: El bloque finally se ejecutar치 siempre, independientemente de que se produzca un error. El bloque finally puede utilizarse para completar la tarea restante o para restablecer las variables que puedan haber cambiado antes de que se produzca el error en el bloque try.

**Example:**

```js
try {
  let lastName = "Yetayeh";
  let fullName = fistName + " " + lastName;
} catch (err) {
  console.log(err);
}
```

```sh
ReferenceError: fistName no est치 definido
    at <anonymous>:4:20
```

```js
try {
  let lastName = "Yetayeh";
  let fullName = fistName + " " + lastName;
} catch (err) {
  console.error(err); // podemos utilizar console.log() o console.error()
} finally {
  console.log("In any case I will be executed");
}
```

```sh
ReferenceError: fistName no est치 definido
    at <anonymous>:4:20
En cualquier caso se ejecutar치
```

El bloque de captura toma un par치metro. Es habitual pasar e, err o error como par치metro al bloque catch. Este par치metro es un objeto y tiene las claves nombre y mensaje. Utilicemos el nombre y el mensaje.

```js
try {
  let lastName = "Yetayeh";
  let fullName = fistName + " " + lastName;
} catch (err) {
  console.log("Name of the error", err.name);
  console.log("Error message", err.message);
} finally {
  console.log("In any case I will be executed");
}
```

```sh
Name of the error ReferenceError
Error message fistName is not defined
In any case I will be executed
```

throw: la sentencia throw nos permite crear un error personalizado. Podemos pasar una cadena, un n칰mero, un booleano o un objeto. Utilice la sentencia throw para lanzar una excepci칩n. Cuando se lanza una excepci칩n, la expresi칩n especifica el valor de la excepci칩n. Cada una de las siguientes acciones lanza una excepci칩n:

```js
throw "Error2"; // genera una excepci칩n con un valor de cadena
throw 42; // genera una excepci칩n con el valor 42
throw true; // genera una excepci칩n con el valor true
throw new Error("Required"); // genera un objeto de error con el mensaje de Requerido
```

```js
const throwErrorExampleFun = () => {
  let message;
  let x = prompt("Enter a number: ");
  try {
    if (x == "") throw "empty";
    if (isNaN(x)) throw "not a number";
    x = Number(x);
    if (x < 5) throw "too low";
    if (x > 10) throw "too high";
  } catch (err) {
    console.log(err);
  }
};
throwErrorExampleFun();
```

### Tipo de Error

- ReferenceError: Se ha producido una referencia ilegal. Se lanza un ReferenceError si utilizamos una variable que no ha sido declarada.

```js
let firstName = "Asabeneh";
let fullName = firstName + " " + lastName;

console.log(fullName);
```

```sh
Uncaught ReferenceError: lastName is not defined
    at <anonymous>:2:35
```

- SyntaxError: Se ha producido un error de sintaxis

```js
let square = 2 x 2
console.log(square)

console.log('Hello, world")
```

```sh
Uncaught SyntaxError: Unexpected identifier
```

- TypeError: Se ha producido un error sobre el tipo

```js
let num = 10;
console.log(num.toLowerCase());
```

```sh
Uncaught TypeError: num.toLowerCase is not a function
    at <anonymous>:2:17
```

Estos son algunos de los errores m치s comunes a los que te puedes enfrentar cuando escribes un c칩digo. Entender los errores puede ayudarte a saber qu칠 errores has cometido y te ayudar치 a depurar tu c칩digo r치pidamente.

游깻 Usted es impecable. Ahora, sabes c칩mo manejar los errores y puedes escribir una aplicaci칩n robusta que maneje entradas inesperadas del usuario. Acabas de completar los desaf칤os del d칤a 14 y llevas 14 pasos en tu camino hacia la grandeza. Ahora haz algunos ejercicios para tu cerebro y para tus m칰sculos.

## Ejercicios

### Ejercicios:Nivel 1

Practica

### Ejercicios:Nivel 2

Practica

### Ejercicios:Nivel 3

Practica

游꿀 춰FELICITACIONES! 游꿀

[<< D칤a 13](../dia_13_Metodos_del_Objeto_Console/dia_13_metodos_del_objeto_console.md) | [D칤a 15>>](..)
